- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Add repository PHP5.6
  apt_repository:
    validate_certs: no
    repo: ppa:ondrej/php
    state: present

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
- name: Repo PG
  shell: curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
- name: Create directory
  file:
    path: /etc/apache2/ssl
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Install a list of packages
  apt:
    pkg:
    - software-properties-common
    - apache2
    - php5.6
    - libapache2-mod-php
    - curl
    - ca-certificates
    - gnupg
    - php5.6-apcu
    - php5.6-common
    - php5.6-curl
    - php5.6-geoip
    - php5.6-imagick
    - php5.6-intl
    - php5.6-mbstring
    - php5.6-mcrypt
    - php5.6-memcache
    - php5.6-memcached
    - php5.6-mongo
    - php5.6-mongodb
    - php5.6-mysql
    - php5.6-sqlite3
    - php5.6-xml
    - php5.6-xsl
    - php5.6-yaml
    - php5.6-zip
    - php5.6-amqp        
    - php5.6-calendar    
    - php5.6-cli         
    - php5.6-ctype       
    - php5.6-dom         
    - php5.6-exif        
    - php5.6-fileinfo    
    - php5.6-ftp         
      #    - php5.6-gmagick     
    - php5.6-iconv       
    - php5.6-igbinary    
    - php5.6-json        
    - php5.6-msgpack     
    - php5.6-opcache     
    - php5.6-pdo         
    - php5.6-pdo-pgsql   
    - php5.6-pgsql       
    - php5.6-phar        
    - php5.6-posix       
    - php5.6-radius      
    - php5.6-readline    
    - php5.6-redis       
    - php5.6-rrd         
    - php5.6-shmop       
    - php5.6-simplexml   
    - php5.6-smbclient   
    - php5.6-soap        
    - php5.6-sockets     
    - php5.6-ssh2        
    - php5.6-sysvmsg     
    - php5.6-sysvsem     
    - php5.6-sysvshm     
    - php5.6-tokenizer   
    - php5.6-wddx        
    - php5.6-xdebug      
    - php5.6-xmlreader   
    - php5.6-xmlwriter   
    - php5.6-xsl         
    - php5.6-zmq         
    - php5.6-calendar 
    - php5.6-cgi      
    - php5.6-cli      
    - php5.6-ctype    
    - php5.6-dom      
    - php5.6-exif     
    - php5.6-fileinfo 
    - php5.6-fpm      
    - php5.6-ftp      
    - php5.6-gd       
    - php5.6-gettext  
    - php5.6-iconv    
    - php5.6-json     
    - php5.6-opcache  
    - php5.6-pdo      
    - php5.6-pdo-pgsql
    - php5.6-pgsql    
    - php5.6-phar     
    - php5.6-posix    
    - php5.6-readline 
    - php5.6-shmop    
    - php5.6-simplexml
    - php5.6-soap     
    - php5.6-sockets  
    - php5.6-sysvmsg  
    - php5.6-sysvsem  
    - php5.6-sysvshm  
    - php5.6-tokenizer
    - php5.6-wddx     
    - php5.6-xdebug   
    - php5.6-xml      
    - php5.6-xmlreader
    - php5.6-xmlwriter
    - php5.6-xsl      
    - net-tools        
    - binutils
    - git 
    - postgresql-client-11
    - npm

- name: Enable mod_rewrite
  shell: a2enmod rewrite && a2enmod ssl && a2enmod headers && a2enmod proxy_http

- name: Enable service apache2, and not touch the state
  service:
    name: apache2
    enabled: yes

- name: Set timezone para Sao Paulo
  timezone:
    name: America/Sao_Paulo
