- name: Create a new primary partition
  parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present

- name: Create a new primary partition
  parted:
    device: /dev/sdc
    number: 1
    flags: [ lvm ]
    state: present

- name: Create a volume group on top of /dev/sdb1 with physical extent size = 32MB
  lvg:
    vg: log-log
    pvs: /dev/sdb1


- name: Create a volume group on top of /dev/sdb1 with physical extent size = 32MB
  lvg:
    vg: app-app
    pvs: /dev/sdc1

- name: Create a logical volume the size of all remaining space in the volume group
  lvol:
    vg: log-log
    lv: log
    pvs: /dev/sdb1
    size: 100%FREE

- name: Create a logical volume the size of all remaining space in the volume group
  lvol:
    vg: app-app
    lv: app
    pvs: /dev/sdc1
    size: 100%FREE


- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Add repository PHP5.6
  apt_repository:
    validate_certs: no
    repo: ppa:ondrej/php
    state: present
   
  
- name: Enable mod_rewrite
  shell: cd /tmp && wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu20.04_all.deb
  
- name: Enable mod_rewrite
  shell: dpkg -i /tmp/zabbix-release_6.0-1+ubuntu20.04_all.deb
  
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
- name: Repo PG
  shell: curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
- name: Create directory
  file:
    path: /etc/apache2/ssl
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Install a list of packages
  apt:
    pkg:
    - software-properties-common
    - apache2
    - php5.6
    - libapache2-mod-php
    - curl
    - ca-certificates
    - gnupg
    - php5.6-apcu
    - php5.6-common
    - php5.6-curl
    - php5.6-geoip
    - php5.6-imagick
    - php5.6-intl
    - php5.6-mbstring
    - php5.6-mcrypt
    - php5.6-memcache
    - php5.6-memcached
    - php5.6-mongo
    - php5.6-mongodb
    - php5.6-mysql
    - php5.6-sqlite3
    - php5.6-xml
    - php5.6-xsl
    - php5.6-yaml
    - php5.6-zip
    - php5.6-amqp        
    - php5.6-calendar    
    - php5.6-cli         
    - php5.6-ctype       
    - php5.6-dom         
    - php5.6-exif        
    - php5.6-fileinfo    
    - php5.6-ftp         
      #    - php5.6-gmagick     
    - php5.6-iconv       
    - php5.6-igbinary    
    - php5.6-json        
    - php5.6-msgpack     
    - php5.6-opcache     
    - php5.6-pdo         
    - php5.6-pdo-pgsql   
    - php5.6-pgsql       
    - php5.6-phar        
    - php5.6-posix       
    - php5.6-radius      
    - php5.6-readline    
    - php5.6-redis       
    - php5.6-rrd         
    - php5.6-shmop       
    - php5.6-simplexml   
    - php5.6-smbclient   
    - php5.6-soap        
    - php5.6-sockets     
    - php5.6-ssh2        
    - php5.6-sysvmsg     
    - php5.6-sysvsem     
    - php5.6-sysvshm     
    - php5.6-tokenizer   
    - php5.6-wddx        
    - php5.6-xdebug      
    - php5.6-xmlreader   
    - php5.6-xmlwriter   
    - php5.6-xsl         
    - php5.6-zmq         
    - php5.6-calendar 
    - php5.6-cgi      
    - php5.6-cli      
    - php5.6-ctype    
    - php5.6-dom      
    - php5.6-exif     
    - php5.6-fileinfo 
    - php5.6-fpm      
    - php5.6-ftp      
    - php5.6-gd       
    - php5.6-gettext  
    - php5.6-iconv    
    - php5.6-json     
    - php5.6-opcache  
    - php5.6-pdo      
    - php5.6-pdo-pgsql
    - php5.6-pgsql    
    - php5.6-phar     
    - php5.6-posix    
    - php5.6-readline 
    - php5.6-shmop    
    - php5.6-simplexml
    - php5.6-soap     
    - php5.6-sockets  
    - php5.6-sysvmsg  
    - php5.6-sysvsem  
    - php5.6-sysvshm  
    - php5.6-tokenizer
    - php5.6-wddx     
    - php5.6-xdebug   
    - php5.6-xml      
    - php5.6-xmlreader
    - php5.6-xmlwriter
    - php5.6-xsl      
    - net-tools        
    - binutils
    - git 
    - postgresql-11
    - npm
    - zabbix-agent2

- name: Change zabbix Server
  lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Server=127.0.0.1'
    line: Server=35.231.38.178
    
- name: Restart service httpd, in all cases
  service:
    name: zabbix-agent2
    state: restarted
    
- name: Enable mod_rewrite
  shell: a2enmod rewrite && a2enmod ssl && a2enmod headers && a2enmod proxy_http

- name: Change zabbix Server
  lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Listen 80'
    line: 'Listen 8081'

- name: Enable service apache2, and not touch the state
  service:
    name: apache2
    enabled: yes

- name: Enable service apache2, and not touch the state
  service:
    name: nginx
    enabled: yes

- name: Restart service httpd, in all cases
  service:
    name: zabbix-agent2
    state: restarted

- name: Set timezone para Sao Paulo
  timezone:
    name: America/Sao_Paulo
